### ISSUE TITLE
Speed up Heroku requests

### ISSUE THREAD

**Issue by LeoDog896** [willuhm-js/OceanFacts#3]
Hello! I had to rewrite your website as it was too slow for my needs. I scraped the database details on my own fork of this website here: [https://github.com/LeoDog896/OceanFacts](https://github.com/LeoDog896/OceanFacts). Of course, if there is a way to speed up heroku, I can help. Just contact me at LeoDog896#0675. Thanks!

**Comment by willuhm-js** [comment]
Hello, thank you for taking interest in this project. Deploying this application for production isn't recommended becaused stored facts are being actively updated and created. If you wish to merge, you may use the PR pipeline and I will approve your changes; attribution for your contributions will be displayed.

**Comment by LeoDog896** [comment]
Wouldn't it be better to store all of the facts in a JSON file then? I doubt there's going to be more than 10k records, and giving it as a JSON file means it can easily be wrappable as a NPM API then something you can capitalize on.

**Comment by willuhm-js** [comment]
I am interested in your suggestions and will contact you. Thanks.
